runtime: python39

handlers:
  # Ruta para archivos est치ticos (HTML, JS, CSS, im치genes, etc.)
  - url: /assets
    static_dir: dist/front-monitoreo/browser/assets

  - url: /media
    static_dir: dist/front-monitoreo/browser/media

   - url: /.*
    static_files: dist/front-monitoreo/browser/index.csr.html
    upload: dist/front-monitoreo/browser/index.csr.html


  # Manejo de archivos est치ticos sin grupos en el patr칩n
  - url: /(.*\.(js|css|html|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot|json))
    static_files: dist/front-monitoreo/browser/\1
    upload: dist/front-monitoreo/browser/.*\.(js|css|html|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot|json)


